version: "3.1"

volumes:
    prometheus_data: {}
    grafana_data: {}
    portainer_data: {}
    influxdb_data: {}
    mariadb_data: {}
    nginx_data: {}
    vscode_data: {}
    unbound_data: {}

networks:
  front-tier:
  back-tier:

services:  
  # =================================================================================
  # ================================= DBs ===========================================
  # =================================================================================
  influxdb:
    container_name: influxdb
    image: influxdb:1.8.5
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - back-tier
    env_file:
      - ./config.env

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.25.2
    restart: unless-stopped
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - ping:ping
      - speedtest:speedtest
      - cadvisor:cadvisor
    networks:
      - back-tier

  mariadb:
    container_name: mariadb
    image: yobasystems/alpine-mariadb:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - back-tier
    env_file:
      - ./config.env

  # =================================================================================
  # ================================= Applications ==================================
  # =================================================================================
  grafana:
    container_name: graphana
    image: grafana/grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
      - influxdb
    ports:
      - 3030:3000
    networks:
      - back-tier
      - front-tier
    env_file:
      - ./config.env

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9000:9000
    networks:
      - back-tier
    depends_on:
      - unbound

  unbound:
    container_name: unbound
    image: klutchell/unbound
    restart: unless-stopped
    volumes:
      - unbound_data:/opt/unbound/etc/unbound/
    ports:
      - 9001:53/udp
      - 9001:53/tcp
  
  pihole:
    container_name: pihole
    privileged: true
    image: pihole/pihole:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - '~/etc-pihole/:/etc/pihole/'
      - '~/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN # Required for running DCHP server
    env_file:
      - ./config.env
  
  nginx:
    container_name: nginx
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'   # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81'   # Admin Web Port
      # - '21:21' # FTP
    volumes:
      - nginx_data:/data
      - nginx_data:/etc/letsencrypt
    depends_on:
      - mariadb
    networks:
      - front-tier
      - back-tier
    env_file:
      - ./config.env

  fan-controller:
    container_name: fan-controller
    image:  ghcr.io/kevalpatel2106/pi-fan-controller:latest
    devices:
      - /dev/gpiomem
    env_file:
      - ./config.env
  
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    env_file:
      - ./config.env
    volumes:
      - vscode_data:/config
    ports:
      - 8443:8443
    restart: unless-stopped

  duckdns:
    image: maksimstojkovic/duckdns
    container_name: duckdns
    network_mode: host
    env_file:
      - ./config.env
    restart: unless-stopped

  # =================================================================================
  # ============================= Graphana Exporters ================================
  # =================================================================================
  
  # ----------------------- Influxdb base monitors -----------------------
  octopusenergy-exporter:
    container_name: octopusenergy-exp
    tty: true
    stdin_open: true
    image: ghcr.io/kevalpatel2106/octopus-consumption-exporter:latest
    restart: unless-stopped
    networks:
      - back-tier
    depends_on:
      - influxdb
    env_file:
      - ./config.env

  # ----------------------- Prometheus base monitors -----------------------
  nodeexp:
    container_name: node-exp
    privileged: true
    image: prom/node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - 9100:9100
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - back-tier

  cadvisor:
    container_name: cadvisor-exp
    image: zcube/cadvisor:latest
    privileged: true
    restart: unless-stopped
    ipc: shareable
    hostname: rpi-cadvisor
    devices:
      - /dev/kmsg
    expose:
      - 8080
    networks:
      - back-tier
    security_opt:
      - label=disable
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
  
  ping:
    container_name: ping-exp
    tty: true
    stdin_open: true
    expose:
      - 9115
    ports:
      - 9115:9115
    image: prom/blackbox-exporter
    restart: unless-stopped
    volumes:
      - ./blackbox/config:/config
    command:
      - '--config.file=/config/blackbox.yml'
    networks:
      - back-tier
  
  speedtest:
    container_name: speedtest-exp
    tty: true
    stdin_open: true
    expose:
      - 9798
    ports:
      - 9798:9798
    image: miguelndecarvalho/speedtest-exporter
    restart: unless-stopped
    networks:
      - back-tier