name: CI
'on':
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    name: Build docker image and test.
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up environment variables
        run: |
          touch config.env
          echo "${{ secrets.CONFIGS }}" >> config.env
      - name: Docker pull
        run: docker-compose pull
        # Fixing DNS Port clash https://github.com/sameersbn/docker-bind/issues/65
      - name: Docker Build
        run: |
          sudo systemctl stop systemd-resolved
          sudo systemctl disable systemd-resolved
          docker-compose up -d
          sleep 10
          docker ps
      - name: Test Prometheus
        run: while ! curl --retry 10 --connect-timeout 5 --retry-delay 5 --retry-max-time 40 -v http://127.0.0.1:9090 >/dev/null; do sleep 1; done
      - name: Test nodexp
        run: while ! curl --retry 10 --connect-timeout 5 --retry-delay 5 --retry-max-time 40 -v http://127.0.0.1:9100 >/dev/null; do sleep 1; done
      - name: Test blackbox exporter (Ping)
        run: while ! curl --retry 10 --connect-timeout 5 --retry-delay 5 --retry-max-time 40 -v http://127.0.0.1:9115 >/dev/null; do sleep 1; done
      - name: Test Speedtest exporter
        run: while ! curl --retry 10 --connect-timeout 5 --retry-delay 5 --retry-max-time 40 -v http://127.0.0.1:9798 >/dev/null; do sleep 1; done
      - name: Test nignix proxy manager
        run: while ! curl --retry 10 --connect-timeout 5 --retry-delay 5 --retry-max-time 40 -v http://127.0.0.1:81 >/dev/null; do sleep 1; done
      - name: Test influxdb set
        run : while ! curl --retry 10 --connect-timeout 5 --retry-delay 5 --retry-max-time 40 -G http://127.0.0.1:8086/query --data-urlencode "q=SHOW DATABASES"> /dev/null; do sleep 1; done
      - name: Test Portainer
        run: while ! curl --retry 10 --connect-timeout 5 --retry-delay 5 --retry-max-time 40 -v http://127.0.0.1:9000 >/dev/null; do sleep 1; done
