name: CI
'on':
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    name: Build docker image and test.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build
        # Fixing DNS Port clash https://github.com/sameersbn/docker-bind/issues/65
        run: |
          docker-compose pull
          sudo systemctl stop systemd-resolved
          sudo systemctl disable systemd-resolved
          docker-compose up -d
          sleep 5
          docker ps
      - name: Test Prometheus
        run: while ! curl --retry 10 --connect-timeout 5 --retry-delay 5 --retry-max-time 40 -v http://127.0.0.1:9090 >/dev/null; do sleep 1; done
      - name: Test nodexp
        run: while ! curl --retry 10 --connect-timeout 5 --retry-delay 5 --retry-max-time 40 -v http://127.0.0.1:9100 >/dev/null; do sleep 1; done
      - name: Test blackbox exporter (Ping)
        run: while ! curl --retry 10 --connect-timeout 5 --retry-delay 5 --retry-max-time 40 -v http://127.0.0.1:9115 >/dev/null; do sleep 1; done
      - name: Test Speedtest exporter
        run: while ! curl --retry 10 --connect-timeout 5 --retry-delay 5 --retry-max-time 40 -v http://127.0.0.1:9798 >/dev/null; do sleep 1; done
      - name: Test Pi-hole
        run: while ! curl --retry 10 --connect-timeout 5 --retry-delay 5 --retry-max-time 40 -v http://127.0.0.1:80 >/dev/null; do sleep 1; done
      - name: Test Portainer
        run: while ! curl --retry 10 --connect-timeout 5 --retry-delay 5 --retry-max-time 40 -v http://127.0.0.1:9000 >/dev/null; do sleep 1; done
